### ISSUE TITLE
Packet Processing Error

### ISSUE THREAD

**Issue by igrowstuff** [Arkay92/PacketFlowAI#2]
On running main.py I get multiple errors, Then the program exits. I can see the scapy packet ok in the debugger.

`Error processing packet: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 1, 1, 2]
`
This is running in capture mode using the WiFi card on a Mac running Sonoma 14.3.1

**Comment by Arkay92** [comment]
Unable to test right now but have updated the shape and removed some extra processing steps let me know if it helps :)

**Comment by igrowstuff** [comment]
Still get same issue

`Error processing packet: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 1, 1, 2]`

**Comment by Arkay92** [comment]
Updated the shape and logic again to match the 2d data after conversion, will spin this back up tomorrow if this latest change doesnt help :)

**Comment by igrowstuff** [comment]
Yes this is running now. I will have a play and hopefully a few PRs. Thanks
